#-Basic info----------------------------------------------------------------------------------------
name: whats_my_species
version: 2.0
#---------------------------------------------------------------------------------------------------

#-Details-------------------------------------------------------------------------------------------
details:
  category: species_detection
  schema_version: 2.0
  target: sample
  type: pipeline
  recommendation: required
  description: >
    This runs kraken/bracken on a sample in order to determine the species found in the sample. Reads
    are first filtered using bbduk. The species is then set for the sample from this.
#---------------------------------------------------------------------------------------------------

#-Docker location-----------------------------------------------------------------------------------
dockerfile: &dockerfile "docker://ssidk/bifrost-whats_my_species:2.0"
#---------------------------------------------------------------------------------------------------

#-Options-------------------------------------------------------------------------------------------
options:
#---------------------------------------------------------------------------------------------------

#-Required resource files---------------------------------------------------------------------------
resources:
  kraken_database: "/bifrost_resources/minikraken_20171019_8GB/"
  kraken_kmer_dist: "/bifrost_resources/minikraken_100mers_distrib.txt"
#---------------------------------------------------------------------------------------------------

#-Requirements to run component---------------------------------------------------------------------
requirements:
  sample:
    properties:
      datafiles:
        paired_reads:
#---------------------------------------------------------------------------------------------------

#-DB Value changes (excluding component output)-----------------------------------------------------
db_values_changes:
  files:
    - whats_my_species/kraken_report.txt
    - whats_my_species/bracken.txt
    - whats_my_species/kraken_report_bracken.txt
  sample:
    properties:
      species_detection:
        summary:  # see sample_component summary
        component:
          _id: 
          date:  # ObjectId
    report:
      species_detection:
  sample_component:
    summary:
      percent_unclassified:
      percent_classified_species_1:
      name_classified_species_1:
      percent_classified_species_2:
      name_classified_species_2 :
      detected_species:
      species:
    results:
      whats_my_species/bracken_txt: {}
      whats_my_species/kraken_report_bracken: {}
      
#---------------------------------------------------------------------------------------------------

