name: Build and push Docker images to Dockerhub
on:
  push:
  release:
    types: [created]

jobs:
    build-n-publish:
      name: Publish Docker 🐳 image 📦 to Dockerhub
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Build and push Docker images (to dev)
        if: github.ref == 'refs/heads/dev'
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # optional
          password: ${{ secrets.DOCKER_PASSWORD }} # optional
          repository: ssidk/${{ github.event.repository.name }}
          tags: dev
          build_args: BUILD_ENV=dev
      - name: Build and push Docker images (to latest)
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # optional
          password: ${{ secrets.DOCKER_PASSWORD }} # optional
          repository: ssidk/${{ github.event.repository.name }}
          tags: latest
      - name: Build and push Docker images (to version)
        if: github.event_name == 'release'
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # optional
          password: ${{ secrets.DOCKER_PASSWORD }} # optional
          repository: ssidk/${{ github.event.repository.name }}
          tags: ${{ github.event.release.tag_name }}__NA # composite of code_version__resource_version
          push: ${{ startsWith(github.ref, 'refs/tags/') }} 
          build_args: CODE_VERSION=${{ github.event.release.tag_name }}
